version: '4.3.1_{build}'

branches:
  only:
    - master

install:
  - ps: |
        $local:MsysPath = "C:\msys64\bin;C:\msys64\usr\bin\"
        $local:GitPaths = ""
        foreach($item in ($env:Path.Split(";") | Group-Object { $_.Contains("Git") -or $_.Contains("cygwin") -or $_.Contains("mingw") -or $_.Contains("MinGW") })){
            if($item.Name -eq $true) {
                $local:GitPaths = $item.Group -join ";"
            }
            else {
                $env:Path = $item.Group -join ";"
            }
        }
        foreach($item in @( $local:MsysPath )){
            if(-Not ($env:Path.Split(";") -contains $item)){
                $env:Path = "$env:Path;$item"
            }
        }
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syu pacman"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-toolchain"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S libtool make"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-{doxygen,cmake}"
  - C:\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -S mingw-w64-x86_64-{eigen,qt5}"
build_script:
  - ps: New-Item -ItemType Directory -Path .\build\MSYS2
  - C:\msys64\usr\bin\bash.exe -lc "MSYSTEM=MINGW64 . /etc/profile; cd /C/projects/imagine-pp/build/MSYS2; /mingw64/bin/cmake -G'Unix Makefiles' ../.. ; make -j4"
